### DISCUSSION TITLE
Vue Flow CSS dependencies

### DISCUSSION THREAD

**Discussion by vvroul** [bcakmakoglu/vue-flow#22] [General]
Hello! I'd like to ask if there are any CSS dependencies that someone should import while setting up the project and the examples. 
I have successfully imported the appropriate styles as stated in the README file, but while trying to run the Basic Example from the examples page, something seems to be missing. 

1. The animated edge is not animated
2. The 'toggle classnames' button doesn't toggle the classes 

Thank you so much! Keep up the great work!

**Comment by bcakmakoglu** [comment]
Hi and thanks for trying out Vueflow :)

Did you import the default theme? The edge animation is part of the default-theme.css file.
```css
/* import the default theme */
@import "node_modules/@braks/vue-flow/dist/theme-default.css";
```

```css
/* default-theme.css */
.vue-flow__edge.animated path {
	stroke-dasharray: 5;
    animation: dashdraw 0.5s linear infinite;
}
```

The toggle is only part of the example so the *dark* nodes have to be styled by yourself, i.e. something like this has to be present in your css:
```css
.vue-flow__node.dark {
  background: #557;
  color: #f8f8f8;
}
```

**Reply by vvroul** [reply]
Hello, thanks for your reply! Yes, I've imported the default theme successfully but it doesn't seem to work. 

Thanks for the clarification on the dark nodes!

**Reply by bcakmakoglu** [reply]
That's strange;
I'm guessing that the postcss format can't be read by your app but I can't be sure about that 😅

What browser are you using?

**Reply by vvroul** [reply]
I'm using Google Chrome. Yeah. must be something wrong with the format.

**Reply by bcakmakoglu** [reply]
Could you try adding the rule manually and see what happens, i.e. add to your custom css:
```css 
.vue-flow__edge.animated path {
	stroke-dasharray: 5;
    animation: dashdraw 0.5s linear infinite;
}
```

 or can you describe the project setup you have?
Are you using vite to build your app? Vite should handle postcss fine without any plugins whatsoever
