### DISCUSSION TITLE
How to implement custom Handle?

### DISCUSSION THREAD

**Discussion by Yeenyeong** [bcakmakoglu/vue-flow#250] [Q&A] [answered]
I want to replace the solid point with some icon. Is there any way to do that?

**Comment by bcakmakoglu** [comment, marked as answer]
The Handle component has a default slot you can fill with anything you like.

```vue
<Handle>
	<CustomHandleContent />
</Handle>
```

Just overwrite the handle styles if necessary and pass your component inside and style it.

```css
.vue-flow__handle {
	height: unset;
	width: unset; /* or whatever you need for your css, this is just an example */
}
```
