### ISSUE TITLE
🐛 [BUG]: Cannot change edge text color

### ISSUE THREAD

**Issue by ocervell** [bcakmakoglu/vue-flow#1614]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I'm trying to override edge text color but it seems I cannot do it.

I've tried:

### Overriding the `.vue-flow__edge-text` CSS style:
```css
.vue-flow__edge-text {
  color: white !important;
}
```

### Adding a Tailwind class on the edge
```ts
let edge = {
  id: `el-${taskName}-${value}`,
  source: value,
  target: taskName,
  label: "test",
  class: "bg-background text-foreground",
  animated: true,
}
```

### Overriding `style`
```ts
let edge = {
  id: `el-${taskName}-${value}`,
  source: value,
  target: taskName,
  label: "test",
  style: { color: 'blue', backgroundColor: 'white' },
  animated: true,
}
```

### Expected Behavior

None of these methods work. I was expecting it to be overridable, just like I can override the label background color with:

```css
.vue-flow__edge-textbg {
  fill: red;
}
```
